main: Improve error printing on exit
Return the Result object gives us better default error output.
Example:

$ sevctl vmsa build ... --firmware idontexist

Before:
  Error: error loading firmware blob entries in OVMF

After:
  Error: error loading firmware blob entries in OVMF

  Caused by:
    0: error reading from firmware path file
    1: No such file or directory (os error 2)

Signed-off-by: Cole Robinson <crobinso@redhat.com>